// SPDX-License-Identifier: MIT

pragma solidity >=0.8.18 <=0.8.23;

/**
 * @title Prevrandao
 * @dev Contract to access the previous RANDAO value
 * @notice This contract provides access to the block's previous RANDAO value and block number
 * @author Daniel Liu <139250065@qq.com>
 */
contract Prevrandao {
    /**
     * @dev Returns the current block number and the previous RANDAO value
     * @return number The current block number
     * @return random The previous RANDAO value from the current block
     * @notice The RANDAO value is a random number generated by the beacon chain
     * @notice This value is used as a source of randomness in the Ethereum network
     */
    function getPrevrandao() external view returns (uint256 number, uint256 random) {
        return (block.number, block.prevrandao);
    }
}
